export const LOGROS_DEF = [
  {
    id: 'racha_7',
    title: 'Racha Semanal',
    description: 'Cumplí tu objetivo de pasos 7 días seguidos.',
    total: 7,
    type: 'bronze',
    icon: 'flame-outline',
    xp: 100,
    getProgress: (p) => Math.min(p?.racha ?? 0, 7),
    resetField: 'racha',
  },
  {
    id: 'gym_10',
    title: 'Visitante Frecuente',
    description: 'Registrá 10 visitas al gimnasio.',
    total: 10,
    type: 'silver',
    icon: 'barbell-outline',
    xp: 150,
    getProgress: (p) => Math.min(p?.gymVisitCount ?? 0, 10),
    resetField: 'gymVisitCount',
  },
  {
    id: 'xp_1000',
    title: 'Primeras 1.000 XP',
    description: 'Alcanzá 1.000 XP en total.',
    total: 1000,
    type: 'gold',
    icon: 'star-outline',
    xp: 200,
    getProgress: (p) => Math.min(p?.xpTotal ?? 0, 1000),
    resetField: 'xpTotal',
  },
];
